### ISSUE TITLE
Metis not building

### ISSUE THREAD

**Issue by sethchandler** [fredrikekre/Metis.jl#1]
I am fairly new to Julia and so there is a good chance this is user error, but  I can not get Metis to build under 0.6.3.  Here's the error message.

Pkg.build("Metis")

INFO: Building CodecZlib
INFO: Building Metis
================================[ ERROR: Metis ]================================

LoadError: UndefVarError: @windows_only not defined
while loading /Users/sethchandler/.julia/v0.6/Metis/deps/build.jl, in expression starting on line 7

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Metis had build errors.

 - packages with build errors remain installed in /Users/sethchandler/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("Metis")`
 - build a single package by running its `deps/build.jl` script

================================================================================

And here is the versioninfo output

Julia Version 0.6.3
Commit d55cadc350 (2018-05-28 20:20 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  WORD_SIZE: 64
  uname: Darwin 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64 i386
Memory: 16.0 GB (403.3359375 MB free)
Uptime: 1.410139e6 sec
Load Avg:  2.5947265625  2.94091796875  2.98095703125
Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3500 MHz    1743451 s          0 s     426655 s    2625231 s          0 s
#2  3500 MHz    1170385 s          0 s     180455 s    3442928 s          0 s
#3  3500 MHz    1810025 s          0 s     373558 s    2610187 s          0 s
#4  3500 MHz    1112692 s          0 s     166397 s    3514676 s          0 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
Environment:
  TERM = xterm-256color
  PATH = /Applications/Julia-0.6.app/Contents/Resources/julia/bin:/Applications/Julia-0.6.app/Contents/Resources/julia/bin:/Users/sethchandler/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
  XPC_FLAGS = 0x0
  HOME = /Users/sethchandler
  FONTCONFIG_PATH = /Applications/Julia-0.6.app/Contents/Resources/julia/etc/fonts

Package Directory: /Users/sethchandler/.julia/v0.6
11 required packages:
 - CSV                           0.2.5
 - DataFrames                    0.11.6
 - GraphDataFrameBridge          0.1.1
 - GraphPlot                     0.2.0
 - HTTP                          0.6.12
 - IJulia                        1.8.0
 - Images                        0.14.0
 - LightGraphs                   0.12.0
 - Metis                         0.0.10
 - QuartzImageIO                 0.3.1
 - Requests                      0.5.1
83 additional packages:
 - AbstractFFTs                  0.3.1
 - AxisAlgorithms                0.2.0
 - AxisArrays                    0.2.1
 - BinDeps                       0.8.8
 - BinaryProvider                0.3.2
 - BufferedStreams               0.4.0
 - Calculus                      0.4.0
 - CatIndices                    0.1.0
 - CategoricalArrays             0.3.10
 - CodecZlib                     0.4.3
 - Codecs                        0.4.0
 - ColorTypes                    0.6.7
 - ColorVectorSpace              0.5.2
 - Colors                        0.8.2
 - Compat                        0.69.0
 - Compose                       0.6.0
 - ComputationalResources        0.2.0
 - Conda                         0.8.1
 - CoordinateTransformations     0.4.1
 - CustomUnitRanges              0.1.0
 - DataStreams                   0.3.6
 - DataStructures                0.8.3
 - Distances                     0.6.0
 - DualNumbers                   0.4.0
 - FFTViews                      0.1.0
 - FFTW                          0.0.4
 - FileIO                        0.9.0
 - FixedPointNumbers             0.4.6
 - Graphics                      0.3.0
 - Graphs                        0.9.0
 - Homebrew                      0.6.3
 - HttpCommon                    0.4.0
 - HttpParser                    0.3.1
 - IdentityRanges                0.1.0
 - ImageAxes                     0.4.0
 - ImageCore                     0.6.0
 - ImageDistances                0.0.2
 - ImageFiltering                0.3.0
 - ImageMetadata                 0.4.0
 - ImageMorphology               0.0.2
 - ImageTransformations          0.4.1
 - IndirectArrays                0.4.2
 - IniFile                       0.4.0
 - InternedStrings               0.6.2
 - Interpolations                0.7.3
 - IntervalSets                  0.2.0
 - IterTools                     0.2.1
 - JLD2                          0.0.6
 - JSON                          0.17.2
 - Libz                          0.2.4
 - MacroTools                    0.4.1
 - MappedArrays                  0.0.7
 - MbedTLS                       0.5.11
 - Measures                      0.2.0
 - MetaGraphs                    0.4.1
 - Missings                      0.2.9
 - NaNMath                       0.3.1
 - NamedTuples                   4.0.2
 - Nullables                     0.0.5
 - OffsetArrays                  0.5.0
 - PaddedViews                   0.3.0
 - ProgressMeter                 0.5.5
 - RangeArrays                   0.2.0
 - Ratios                        0.2.0
 - Reexport                      0.1.0
 - Requires                      0.4.4
 - Rotations                     0.7.0
 - SHA                           0.5.7
 - SIUnits                       0.1.0
 - ShowItLikeYouBuildIt          0.2.0
 - SimpleTraits                  0.6.0
 - SortingAlgorithms             0.2.1
 - SpecialFunctions              0.5.0
 - StaticArrays                  0.7.1
 - StatsBase                     0.23.0
 - TexExtensions                 0.1.0
 - TiledIteration                0.1.0
 - TranscodingStreams            0.5.2
 - URIParser                     0.3.1
 - VersionParsing                1.1.1
 - WeakRefStrings                0.4.7
 - WoodburyMatrices              0.2.2
 - ZMQ                           0.6.2

Pkg.update()
INFO: Updating METADATA...
INFO: Computing chan

**Comment by fredrikekre** [comment]
Looks like you are using https://github.com/JuliaSparse/Metis.jl?
This repo (https://github.com/fredrikekre/Metis.jl) is an updated version, which not yet replaces the old one. If you are on Linux or macOS you can use this repo instead, I have not yet set up Windows support. Looks like you are on macOS so try to first remove the other repo and add this one with 
```
Pkg.clone("https://github.com/fredrikekre/Metis.jl.git")
```

**Comment by sethchandler** [comment]
Success!  Thanks for your help and for your work on the METIS package.
