### ISSUE TITLE
Getting METIS_PartGraphKway to work

### ISSUE THREAD

**Issue by sethchandler** [fredrikekre/Metis.jl#2]
As shown in the attached notebook, I am having difficulty getting METIS_PartGraphKway to work. I am getting the following error. Am I doing something wrong? What do I need to do to directly access the C API?

UndefVarError: METIS_PartGraphKway not defined

[Getting Metis partition to work.ipynb.zip](https://github.com/fredrikekre/Metis.jl/files/2127982/Getting.Metis.partition.to.work.ipynb.zip)

**Comment by fredrikekre** [comment]
`METIS_PartGraphKway` is not exported, so you will have to either do
```
using Metis: METIS_PartGraphKway
```
once, or you prefix it with the module name every time you call the function
```
Metis.METIS_PartGraphKway
```
Does that fix your issue?

**Comment by sethchandler** [comment]
I am sorry, but I am still having problems. Every time I call the function, the Julia kernel crashes. Might you provide an example or two showing the correct usage of the function Metis.METIS_PartGraphKway for a graph that has vertex weights, edgeweights, desired partition fractions, and an "ubvec" limitation on the deviations of the total weightings of the partitions?
